# add config from DavidAnsons Markdownlint library config
{
  "default": true,
  "MD007": { "indent": 4 },
  "MD026": false,
  "MD013": false,
  "MD014": false,
  "MD041": false,
  "MD033": false,
  "MD035": false,
  "MD040": false,
  "MD045": false,
  "MD024": false,
  "no-hard-tabs": false,
}